### ISSUE TITLE
SPLiT-seq corrections

### ISSUE THREAD

**Issue by arnavm** [Teichlab/scg_lib_structs#13]
Hi,

I've noticed some differences in the oligonucleotide sequences for SPLiT-seq between different protocol versions.

This is the structure of read2 based on the [preprint](https://www.biorxiv.org/content/10.1101/105163v1), which matches what you currently have:
`[10-bp UMI][8-bp Round3 barcode]GTGGCCGATGTTTCGCATCGGCGTACGACT[8-bp Round2 barcode]ATCCACGTGCTTGAGCGCGCTGCATACTTG[8-bp Round1 barcode]CCCATGATCGTCCGAAGGCCAGAGCATTCG(dT)`

This is the structure of read2 based on the [published](https://www.science.org/doi/10.1126/science.aam8999) manuscript:
`[10-bp UMI][8-bp Round3 barcode]GTGGCCGATGTTTCGCATCGGCGTACGACT[8-bp Round2 barcode]ATCCACGTGCTTGAGAGGCCAGAGCATTCG[8-bp Round1 barcode](dT or N6)`. This sequence ends with either  `poly(dT)VN` or `NNNNNN` depending on if the oligo primes off poly(A) or random hexamers. I don't know why the oligo design changed between preprint and acceptance.

Finally, the oligo design has changed again in the commercial version of SPLiT-seq by Parse BioSciences. This is the new read2 structure:
`[10-bp UMI][8-bp Round3 barcode]GTGGCCGATGTTTCGCATCGGCGTACGACT[8-bp Round2 barcode]ATCCACGTGCTTGAGACTGTGG[8-bp Round1 barcode](dT)`

As far as I can tell, all three versions have a 6 bp i7 index between the Illumina TruSeq and P7 sequences.

**Comment by dbrg77** [comment]
Hi Arnav,

I have now archived the old SPLiT-seq page, and create a new SPLiT-seq page based on the `science2018` publication. Both of them are can be accessed. In addition, I also point to this thread to let people know that there is a commercial version of the method.

Closing for now, but feel free to re-open.

Xi

**Comment by vitalinace** [comment]
Hello! Do you know by chance the sequence of the RT primers (1st barcode round) used in the commercial version by Parse? I am interested in the adaptor sequence in the RT primer used for the following ligation of 2nd barcode

**Comment by dbrg77** [comment]
Hi @vitachambev 

I missed the comment the other day. Unfortunately, I don't have information. There are no `fastq` files on their website last time I checked, and the kits are not available in China.

I might check with them to see if that's something they can share. In the meantime, maybe @arnavm knows ???

Regards,
Xi
