### ISSUE TITLE
Multiome Correction

### ISSUE THREAD

**Issue by dannyconrad** [Teichlab/scg_lib_structs#15]
With the release of the v2 scATAC-sq kit, I think we have some additional information to supplement/improve the Multiome schematics. The new ATAC kit uses the same enzyme as the Multiome kit (ATAC Enzyme B, PN 2000265). If the schematics at the end of the v2 protocol are accurate, this means there isn't any modification to the enzyme or its adapter sequences. This suggests that the spacer sequence in the capture oligo enables hybridization of a separate splint oligo, which in turn facilitates the ligation of the gDNA fragment to the capture oligo. The splint oligo is not mentioned anywhere but I think this is the logical conclusion. 

I assume that what makes ATAC Enzyme B different is instead just that it is more concentrated, a change they probably had to make to improve sensitivity in the Multiome kit that also enabled them to cut the transposition time in the v2 ATAC kit from 60 -> 30 minutes.

**Comment by dbrg77** [comment]
Thanks @dannyconrad for the heads up.

Indeed, if the enzyme in the scATAC v2 kit and the Multiome kit is the same, the presence of a splint oligo makes more sense. A more concentrated version of Tn5 was used in the Bio-Rad dscATAC/dsciATAC which has been shown to improve the quality metrics, so it is also reasonable to assume the scATAC v2 kit and the Multiome kit use a more concentrated version.

I will update soon.

Thank you.

Xi

**Comment by dannyconrad** [comment]
Thanks Xi! And thank you as well for helping to build such a wonderful tool. I've used this resource many times and have recommended the schematics to many others to help understand library construction across methods.

**Comment by dannyconrad** [comment]
Hey @dbrg77, had another thought while working through the schematics. 

Ligation requires a 5' phosphate. This means one of two things: 
1. The Nextera R1 adapter loaded into the ATAC Enzyme B has been modified to contain a 5' phosphate
2. The splint oligo used to bridge the gDNA fragments to the capture oligo has a 5' phosphate

I suppose both could be true but this seems unlikely. Unless I'm mistaken, either method should result in a library that can be permanently barcoded with the gap-fill reaction at 72˚C, but I would assume they would choose to modify the splint oligo rather than modifying the enzyme? Curious to hear your thoughts. 

Here is a schematic:
![image](https://user-images.githubusercontent.com/22381421/176718928-56c203df-d1f8-4536-bec6-3083e8942d83.png)

**Comment by dannyconrad** [comment]
Ah, SNARE-seq uses a 5' phosphate on the splint, so I assume that's what 10X copied.

**Comment by dbrg77** [comment]
Hi @dannyconrad , thanks very much for the post! You already figure out the details for me, lol

The SNARE-seq-like splint/bridging oligo you drew above makes sense and it would be straightforward for them to do that without doing too many modifications. In a regular Tn5 setting for ATAC-seq, the transfer strand is longer (19bp ME + 14 or 15 bp primer entry points), and the non-transfer strand (the one next to the gap) is short, basically 19bp ME.

The reason that I thought they change the Tn5 is the drawing in their [Multiome user guide](https://teichlab.github.io/scg_lib_structs/data/CG000338_ChromiumNextGEM_Multiome_ATAC_GEX_User_Guide_RevB.pdf). Check Page 79:

<img width="780" alt="Screenshot 2022-07-02 at 17 18 47" src="https://user-images.githubusercontent.com/7750032/176994487-e4feda52-8662-4ec2-af5d-66135ee9e9f4.png">

In this drawing, it seems the transfer strand is shorter and the non-transfer strand is longer, not sure if I should take this drawing seriously ...

For the time being, I will update the page with the splint oligo you draw. In the meantime, I will do some further reading.

Thanks.

Regards,
Xi

**Comment by dbrg77** [comment]
Oh, never mind. I guess they made a mistake. The picture in the above post is from the RevB of their user guide. In the latest user guid (RevE), page 80, it is the same as the regular ATAC, i.e. the transfer strand is the longer one:

<img width="1732" alt="Screenshot 2022-07-02 at 20 58 13" src="https://user-images.githubusercontent.com/7750032/177001747-6af40657-6b74-4b25-bb5e-4fe17c613fa0.png">

**Comment by dbrg77** [comment]
I guess this should be correct. Closing for now.
Feel free to re-open, otherwise.
