### ISSUE TITLE
Little mistake

### ISSUE THREAD

**Issue by paddle-salted-fish** [Teichlab/scg_lib_structs#16]
Thanks very much for your work. It helps me a lot.
There is a mistake in Microwell-seq. In the sequence TSO_LNA, the first base in 3' end is LNA-G, not rG (By the way, the authors possibly made this mistake in their article). The corrected primer should be: 
5'- AAGCAGTGGTATCAACGCAGAGTGAATrGrG+G

**Comment by dbrg77** [comment]
Thanks for spotting the error. Indeed, it makes sense, otherwise, it won't called TSO-LNA, lol

Corrected now!
