### ISSUE TITLE
"suppressiev" typos in smart-seq protocols page 

### ISSUE THREAD

**Issue by Romain-B** [Teichlab/scg_lib_structs#18]
Hello,
Thanks for this great resource you've made!

There are a few (5) instances of typos for "semi-suppressive PCR", written as "semi-suppressiev PCR" in the Smart-seq protocols page:
https://teichlab.github.io/scg_lib_structs/methods_html/SMART-seq_family.html

Best,
Romain

**Comment by dbrg77** [comment]
Thank you @Romain-B 

Corrected now! I'm sure there are many other typos. Will correct when spotting them.

Thanks again.
