### ISSUE TITLE
Citing

### ISSUE THREAD

**Issue by TyberiusPrime** [Teichlab/scg_lib_structs#19]
This is an very useful resource, thank you very much.

What's your preferred method for citing this in scientific articles?

Prehaps you can do 'releases' and have them assigned a doi?
https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

Take care!

**Comment by dbrg77** [comment]
Thanks for the suggestion, @TyberiusPrime 

I haven't thought about this. Now I will create a release and get a DOI. I think the preferred way is to cite this repo together with the [seqspec](https://www.biorxiv.org/content/10.1101/2023.03.17.533215v2) manuscript. I will soon add a citation section in the README.

Thanks again, and it is always nice to hear that the repo is helpful to people in the field :-)

**Comment by dbrg77** [comment]
Okay, this has been done. Closing now.

Thanks!
