### ISSUE TITLE
Want to expand the repo's utility but need git lfs enable to push on fork

### ISSUE THREAD

**Issue by Hoohm** [Teichlab/scg_lib_structs#3]
Hello @dbrg77

Thank you for this centralized repo of goodies regarding single-cell protocols.

I'm trying to expand the capacities/utility of the repo.
In order to do this, I wanted to upload a large file (200M) of a 10x v3 whitelist using git lfs. it seems that I cannot do this if the main repo from which I fork has not git lfs capacities. https://github.com/git-lfs/git-lfs/issues/1449

Would it be possible to add this?

**Comment by dbrg77** [comment]
Hi @Hoohm ,

Thanks you for the advice. I'm not familiar with git-lfs. I used it once in the past. It was working at the beginning but then complains that I have used my bandwidth.

I think the whitelist is in the cellranger software, so people can simply find it there. Do you think using git-lfs is better than finding it from the celllranger software?

You just remind me that I forgot to point out where the file is in the V3 chemistry. I will add it to the page. For the whitelist you mentioned, is this file that you are talking about: `cellranger-cs/3.1.0/lib/python/cellranger/barcodes/3M-february-2018.txt.gz`?

Thanks.

Regards,
Xi

**Comment by Hoohm** [comment]
Hey @dbrg77 ,

I actually have a prepared PR for you, I couldn't push it to my fork because of this git-lfs issue.

I rewrote it without it. The only reason I needed git-lfs is because of the whitelist being 200M.

I'll switch the discussion to the PR instead of the issue if that's ok with you. I want to explain why I would like to group this information into a repo rather than dispersed over multiple websites/repos.
