### ISSUE TITLE
Mars-Seq cell barcode/ UMI size

### ISSUE THREAD

**Issue by Bernadetadad** [Teichlab/scg_lib_structs#5]
Based on MARS-Seq [page](http://compgenomics.weizmann.ac.il/tanay/?page_id=672)(see RT1 primers) cell barcodes are 7nt and UMIs are 8nt.

**Comment by dbrg77** [comment]
Thanks @Bernadetadad , I did not realised that they have a website for MARS-seq. Now updated the MARS-seq2.0.
