### ISSUE TITLE
cDNA tagmentation and library amplification step for Split-seq

### ISSUE THREAD

**Issue by MinjieHu** [Teichlab/scg_lib_structs#9]
Hi guys,

Thanks for the awesome resources for modern sequencing technologies. It indeed help a lot to understand the design behinds different technologies!

I looked into the detailed steps for the Split-Seq and got a little confused about the cDNA tagmentation and library amplification step. In your illustration, after tagmentation, there will be a product have s5 at both ends (as showed below).
![image](https://user-images.githubusercontent.com/39601931/88680782-dee2f180-d0be-11ea-932b-faaea7e0cea5.png)

As you mentioned, this product is not amplifiable due to PCR primers used. However, I think one of the PCR primers can binding to the both ends (blow is the binding of one ends, the other ends should be the same).
![image](https://user-images.githubusercontent.com/39601931/88681410-8a8c4180-d0bf-11ea-967b-1007d78d2545.png)
If this is true, this product could also be amplified solely by one primer. Could you help to clarify?

Thanks in advance.

Minjie

**Comment by dbrg77** [comment]
Hi Minjie,

Thanks for your question. Just use the fragment with s5 at both ends as an example. After gap fill-in, the example you gave will be like this:

![Screenshot 2020-07-29 at 13 07 13](https://user-images.githubusercontent.com/7750032/88759128-a87ba400-d19c-11ea-9802-583ee0912a34.png)

If you notice, the S5 + ME (blue + grey) sequence is invert-repeats, meaning that in both the top and the bottom strands, the 5' end and the 3' end are reverse complementary to each other. Therefore, during PCR, bot the top strand and the bottom strand will form a hairpin loop structure like this:

![Fold](https://user-images.githubusercontent.com/7750032/88759333-1c1db100-d19d-11ea-9d09-4881eb542553.png)

When the insert is short which is often the case after tagmentation (I'm not sure how "short" is short), this intra-molecular hairpin structure is a much favoured structure. This prevent primer binding and further amplification. When the insert is long, it can be amplified using one primer. This is called semi-suppressive PCR. For example, check this paper: http://www.nature.com/nmeth/journal/v7/n7/full/nmeth.1470.html.

Quite a while ago, I tried doing PCR comparing using s5/s7 primers and only single primers (s5 or s7) after tagmentation, and the Ct difference is huge, like 10-Ct away, which is 1024 times difference. This is the result:

![431596000022_ pic_hd](https://user-images.githubusercontent.com/7750032/88759958-8aaf3e80-d19e-11ea-8438-f3eda6679a74.jpg)

I guess they will be some sort of amplification by just one primer, but it is really inefficient and the resulting fragment will have both P5 or P7 at both ends, which won't get sequenced by Illumina sequencing.

I hope this is clear.

Regards,
Xi

**Comment by MinjieHu** [comment]
Hi Xi,

This is super clear and totally make sense!

For the fragment size after tagmentation, I have tried once with Split-seq and found the fragment size is quite broad, and the peak size is around 1000bp.

Minjie
